<?php

return [
    'modules' => [
        ['id' => 1, 'key' => 'dashboard', 'name' => 'Dashboard', 'sort_order' => 10],
        ['id' => 2, 'key' => 'cms', 'name' => 'CMS', 'sort_order' => 20],
        ['id' => 3, 'key' => 'db_diagram', 'name' => 'DB Diagram', 'sort_order' => 30],
        ['id' => 4, 'key' => 'settings', 'name' => 'Instellingen', 'sort_order' => 40],
        ['id' => 5, 'key' => 'menu_configuration', 'name' => 'Menu configuratie', 'sort_order' => 50],
        ['id' => 6, 'key' => 'permissions', 'name' => 'Permissions', 'sort_order' => 60],
        ['id' => 7, 'key' => 'query_builder', 'name' => 'Query Builder', 'sort_order' => 70],
        ['id' => 8, 'key' => 'roles', 'name' => 'Roles', 'sort_order' => 80],
        ['id' => 9, 'key' => 'run', 'name' => 'Run', 'sort_order' => 90],
        ['id' => 10, 'key' => 'screen_builder', 'name' => 'Screen Builder', 'sort_order' => 100],
        ['id' => 11, 'key' => 'users', 'name' => 'Users', 'sort_order' => 110],
    ],

    'actions' => [
        ['id' => 1, 'key' => 'create', 'name' => 'Aanmaken', 'sort_order' => 10],
        ['id' => 2, 'key' => 'activate', 'name' => 'Activeren', 'sort_order' => 20],
        ['id' => 3, 'key' => 'manage', 'name' => 'Beheer', 'sort_order' => 30],
        ['id' => 4, 'key' => 'save', 'name' => 'Bewaren', 'sort_order' => 40],
        ['id' => 5, 'key' => 'edit', 'name' => 'Bewerken', 'sort_order' => 50],
        ['id' => 6, 'key' => 'client_rules_editor', 'name' => 'Client Rules Editor', 'sort_order' => 60],
        ['id' => 7, 'key' => 'load_code', 'name' => 'Code laden', 'sort_order' => 70],
        ['id' => 8, 'key' => 'manage_codeblocks', 'name' => 'Codeblocks beheren', 'sort_order' => 80],
        ['id' => 9, 'key' => 'download', 'name' => 'Downloaden', 'sort_order' => 90],
        ['id' => 10, 'key' => 'export', 'name' => 'Export', 'sort_order' => 100],
        ['id' => 11, 'key' => 'restore', 'name' => 'Herstellen', 'sort_order' => 110],
        ['id' => 12, 'key' => 'import', 'name' => 'Importeren', 'sort_order' => 120],
        ['id' => 13, 'key' => 'inspect', 'name' => 'Inspecteren', 'sort_order' => 130],
        ['id' => 14, 'key' => 'view_quality', 'name' => 'Kwaliteit bekijken', 'sort_order' => 140],
        ['id' => 15, 'key' => 'public_text_ai', 'name' => 'Openbare teksten AI', 'sort_order' => 150],
        ['id' => 16, 'key' => 'update_public_texts', 'name' => 'Openbare teksten bijwerken', 'sort_order' => 160],
        ['id' => 17, 'key' => 'load_public_texts', 'name' => 'Openbare teksten laden', 'sort_order' => 170],
        ['id' => 18, 'key' => 'sync_public_texts', 'name' => 'Openbare teksten sync', 'sort_order' => 180],
        ['id' => 19, 'key' => 'index', 'name' => 'Overzicht', 'sort_order' => 190],
        ['id' => 20, 'key' => 'preview', 'name' => 'Preview', 'sort_order' => 200],
        ['id' => 21, 'key' => 'publish', 'name' => 'Publiceren', 'sort_order' => 210],
        ['id' => 22, 'key' => 'run', 'name' => 'Run', 'sort_order' => 220],
        ['id' => 23, 'key' => 'add_language', 'name' => 'Taal toevoegen', 'sort_order' => 230],
        ['id' => 24, 'key' => 'update_languages', 'name' => 'Talen bijwerken', 'sort_order' => 240],
        ['id' => 25, 'key' => 'language_editor', 'name' => 'Talen editor', 'sort_order' => 250],
        ['id' => 26, 'key' => 'load_languages', 'name' => 'Talen laden', 'sort_order' => 260],
        ['id' => 27, 'key' => 'sync_languages', 'name' => 'Talen sync', 'sort_order' => 270],
        ['id' => 28, 'key' => 'add', 'name' => 'Toevoegen', 'sort_order' => 280],
        ['id' => 29, 'key' => 'restore_version', 'name' => 'Versie herstellen', 'sort_order' => 290],
        ['id' => 30, 'key' => 'view_versions', 'name' => 'Versies bekijken', 'sort_order' => 300],
        ['id' => 31, 'key' => 'translate', 'name' => 'Vertalen', 'sort_order' => 310],
        ['id' => 32, 'key' => 'delete', 'name' => 'Verwijderen', 'sort_order' => 320],
        ['id' => 34, 'key' => 'sort', 'name' => 'Sorteren', 'sort_order' => 340],
    ],

    'types' => [
        ['id' => 1, 'key' => 'core', 'name' => 'Core', 'sort_order' => 10],
    ],
];
