<?php

return [
    'storage_disk' => env('CMS_THEME_STORAGE_DISK', 'local'),

    'css' => [
        'allow_external_assets' => true,
        'allow_imports' => false,
        'allowed_external_schemes' => ['https'],
        'allowed_external_hosts' => array_filter(array_map(
            'trim',
            explode(',', (string) env('CMS_THEME_ALLOWED_EXTERNAL_HOSTS', 'fonts.bunny.net,cdn.jsdelivr.net'))
        )),
        'allowed_asset_extensions' => ['woff2', 'woff', 'png', 'jpg', 'jpeg', 'webp', 'avif'],
        'blocked_schemes' => ['javascript', 'data', 'file', 'ftp'],
        'max_css_bytes' => 400000,
    ],

    'import' => [
        'allowed_paths' => ['manifest.json', 'css/', 'settings/', 'assets/'],
        'allowed_extensions' => ['json', 'css', 'png', 'jpg', 'jpeg', 'webp', 'avif'],
    ],

    'font_family_tokens' => [
        'inherit' => 'Inherit',
        'body' => 'Body',
        'heading' => 'Heading',
        'brand' => 'Brand',
        'accent' => 'Accent',
    ],

    'font_size_tokens' => [
        'inherit' => 'Inherit',
        'body' => 'Body',
        'small' => 'Small',
        'nav' => 'Navigation',
        'brand' => 'Brand',
        'baseline' => 'Baseline',
    ],

    'font_weight_tokens' => [
        'inherit' => 'Inherit',
        'normal' => 'Normal',
        'medium' => 'Medium',
        'semibold' => 'Semibold',
        'bold' => 'Bold',
    ],

    'typography_preset_tokens' => [
        'inherit' => 'Inherit',
        'h1' => 'H1',
        'h2' => 'H2',
        'h3' => 'H3',
        'h4' => 'H4',
        'h5' => 'H5',
        'h6' => 'H6',
        'body' => 'Body',
        'lead' => 'Lead',
        'small' => 'Small',
        'caption' => 'Caption',
        'eyebrow' => 'Eyebrow',
    ],

    'color_tokens' => [
        'page' => 'Page background',
        'surface' => 'Surface',
        'surface-muted' => 'Muted surface',
        'text' => 'Text',
        'muted' => 'Muted text',
        'border' => 'Border',
        'primary' => 'Primary',
        'primary-strong' => 'Primary strong',
        'primary-contrast' => 'Primary contrast',
        'success' => 'Success',
        'success-bg' => 'Success background',
        'error' => 'Error',
        'error-bg' => 'Error background',
    ],

    'settings_fields' => [
        ['key' => 'page_background', 'label' => 'Pagina achtergrond', 'type' => 'color', 'default' => '#f8fafc', 'css_variable' => '--rw-public-color-page'],
        ['key' => 'surface_background', 'label' => 'Kaart achtergrond', 'type' => 'color', 'default' => '#ffffff', 'css_variable' => '--rw-public-color-surface'],
        ['key' => 'surface_muted_background', 'label' => 'Subtiele achtergrond', 'type' => 'color', 'default' => '#f1f5f9', 'css_variable' => '--rw-public-color-surface-muted'],
        ['key' => 'text_color', 'label' => 'Tekstkleur', 'type' => 'color', 'default' => '#0f172a', 'css_variable' => '--rw-public-color-text'],
        ['key' => 'muted_text_color', 'label' => 'Secundaire tekstkleur', 'type' => 'color', 'default' => '#475569', 'css_variable' => '--rw-public-color-muted'],
        ['key' => 'primary_color', 'label' => 'Primaire kleur', 'type' => 'color', 'default' => '#2563eb', 'css_variable' => '--rw-public-color-primary'],
        ['key' => 'primary_strong_color', 'label' => 'Primaire hoverkleur', 'type' => 'color', 'default' => '#1d4ed8', 'css_variable' => '--rw-public-color-primary-strong'],
        ['key' => 'primary_contrast_color', 'label' => 'Tekst op primaire kleur', 'type' => 'color', 'default' => '#ffffff', 'css_variable' => '--rw-public-color-primary-contrast'],
        ['key' => 'body_font_family', 'label' => 'Body lettertype', 'type' => 'text', 'default' => 'Inter, ui-sans-serif, system-ui, sans-serif', 'css_variable' => '--rw-public-font-body'],
        ['key' => 'heading_font_family', 'label' => 'Heading font', 'type' => 'text', 'default' => 'var(--rw-public-font-body)', 'css_variable' => '--rw-public-font-heading'],
        ['key' => 'brand_font_family', 'label' => 'Brand font', 'type' => 'text', 'default' => 'var(--rw-public-font-heading)', 'css_variable' => '--rw-public-font-brand'],
        ['key' => 'accent_font_family', 'label' => 'Accent font', 'type' => 'text', 'default' => 'var(--rw-public-font-heading)', 'css_variable' => '--rw-public-font-accent'],
        ['key' => 'body_font_size', 'label' => 'Body tekstgrootte', 'type' => 'text', 'default' => '1rem', 'css_variable' => '--rw-public-font-size-body', 'selector' => 'body.rw-public', 'property' => 'font-size'],
        ['key' => 'small_font_size', 'label' => 'Small text size', 'type' => 'text', 'default' => '0.875rem', 'css_variable' => '--rw-public-font-size-small'],
        ['key' => 'nav_font_size', 'label' => 'Navigation text size', 'type' => 'text', 'default' => '0.95rem', 'css_variable' => '--rw-public-font-size-nav'],
        ['key' => 'brand_font_size', 'label' => 'Brand text size', 'type' => 'text', 'default' => '1.35rem', 'css_variable' => '--rw-public-font-size-brand'],
        ['key' => 'baseline_font_size', 'label' => 'Baseline text size', 'type' => 'text', 'default' => '0.9rem', 'css_variable' => '--rw-public-font-size-baseline'],
        ['key' => 'body_line_height', 'label' => 'Body lijnhoogte', 'type' => 'text', 'default' => '1.6', 'selector' => 'body.rw-public', 'property' => 'line-height'],
        ['key' => 'container_width', 'label' => 'Container breedte', 'type' => 'text', 'default' => '1440px', 'css_variable' => '--rw-public-container-width'],
        ['key' => 'radius_small', 'label' => 'Kleine radius', 'type' => 'text', 'default' => '0.75rem', 'css_variable' => '--rw-public-radius-sm'],
        ['key' => 'radius_medium', 'label' => 'Medium radius', 'type' => 'text', 'default' => '1rem', 'css_variable' => '--rw-public-radius-md'],
        ['key' => 'radius_large', 'label' => 'Grote radius', 'type' => 'text', 'default' => '1.5rem', 'css_variable' => '--rw-public-radius-lg'],
        ['key' => 'h1_font_family', 'label' => 'H1 lettertype', 'type' => 'text', 'default' => 'inherit', 'selector' => '.rw-public-title', 'property' => 'font-family'],
        ['key' => 'h1_font_size', 'label' => 'H1 grootte', 'type' => 'text', 'default' => 'clamp(2.4rem, 7vw, 5rem)', 'selector' => '.rw-public-title', 'property' => 'font-size'],
        ['key' => 'h1_line_height', 'label' => 'H1 lijnhoogte', 'type' => 'text', 'default' => '0.95', 'selector' => '.rw-public-title', 'property' => 'line-height'],
        ['key' => 'h1_color', 'label' => 'H1 kleur', 'type' => 'color', 'default' => '#0f172a', 'selector' => '.rw-public-title', 'property' => 'color'],
        ['key' => 'h2_font_size', 'label' => 'H2/bloktitel grootte', 'type' => 'text', 'default' => 'clamp(1.45rem, 3vw, 2.2rem)', 'selector' => '.rw-public-block__title, .rw-public-form__title', 'property' => 'font-size'],
        ['key' => 'h2_color', 'label' => 'H2/bloktitel kleur', 'type' => 'color', 'default' => '#0f172a', 'selector' => '.rw-public-block__title, .rw-public-form__title', 'property' => 'color'],
        ['key' => 'typo_h1_font_family', 'label' => 'H1 typography font', 'type' => 'text', 'default' => 'var(--rw-public-font-heading)', 'css_variable' => '--rw-public-typo-h1-font-family'],
        ['key' => 'typo_h1_font_size', 'label' => 'H1 typography size', 'type' => 'text', 'default' => 'clamp(2.4rem, 7vw, 5rem)', 'css_variable' => '--rw-public-typo-h1-font-size'],
        ['key' => 'typo_h1_font_weight', 'label' => 'H1 typography weight', 'type' => 'text', 'default' => '800', 'css_variable' => '--rw-public-typo-h1-font-weight'],
        ['key' => 'typo_h1_line_height', 'label' => 'H1 typography line height', 'type' => 'text', 'default' => '0.95', 'css_variable' => '--rw-public-typo-h1-line-height'],
        ['key' => 'typo_h1_letter_spacing', 'label' => 'H1 typography letter spacing', 'type' => 'text', 'default' => '-0.06em', 'css_variable' => '--rw-public-typo-h1-letter-spacing'],
        ['key' => 'typo_h2_font_family', 'label' => 'H2 typography font', 'type' => 'text', 'default' => 'var(--rw-public-font-heading)', 'css_variable' => '--rw-public-typo-h2-font-family'],
        ['key' => 'typo_h2_font_size', 'label' => 'H2 typography size', 'type' => 'text', 'default' => 'clamp(1.9rem, 4.8vw, 3.5rem)', 'css_variable' => '--rw-public-typo-h2-font-size'],
        ['key' => 'typo_h2_font_weight', 'label' => 'H2 typography weight', 'type' => 'text', 'default' => '750', 'css_variable' => '--rw-public-typo-h2-font-weight'],
        ['key' => 'typo_h2_line_height', 'label' => 'H2 typography line height', 'type' => 'text', 'default' => '1.05', 'css_variable' => '--rw-public-typo-h2-line-height'],
        ['key' => 'typo_h2_letter_spacing', 'label' => 'H2 typography letter spacing', 'type' => 'text', 'default' => '-0.045em', 'css_variable' => '--rw-public-typo-h2-letter-spacing'],
        ['key' => 'typo_h3_font_family', 'label' => 'H3 typography font', 'type' => 'text', 'default' => 'var(--rw-public-font-heading)', 'css_variable' => '--rw-public-typo-h3-font-family'],
        ['key' => 'typo_h3_font_size', 'label' => 'H3 typography size', 'type' => 'text', 'default' => 'clamp(1.55rem, 3.4vw, 2.45rem)', 'css_variable' => '--rw-public-typo-h3-font-size'],
        ['key' => 'typo_h3_font_weight', 'label' => 'H3 typography weight', 'type' => 'text', 'default' => '700', 'css_variable' => '--rw-public-typo-h3-font-weight'],
        ['key' => 'typo_h3_line_height', 'label' => 'H3 typography line height', 'type' => 'text', 'default' => '1.12', 'css_variable' => '--rw-public-typo-h3-line-height'],
        ['key' => 'typo_h3_letter_spacing', 'label' => 'H3 typography letter spacing', 'type' => 'text', 'default' => '-0.03em', 'css_variable' => '--rw-public-typo-h3-letter-spacing'],
        ['key' => 'typo_h4_font_family', 'label' => 'H4 typography font', 'type' => 'text', 'default' => 'var(--rw-public-font-heading)', 'css_variable' => '--rw-public-typo-h4-font-family'],
        ['key' => 'typo_h4_font_size', 'label' => 'H4 typography size', 'type' => 'text', 'default' => 'clamp(1.3rem, 2.4vw, 1.8rem)', 'css_variable' => '--rw-public-typo-h4-font-size'],
        ['key' => 'typo_h4_font_weight', 'label' => 'H4 typography weight', 'type' => 'text', 'default' => '700', 'css_variable' => '--rw-public-typo-h4-font-weight'],
        ['key' => 'typo_h4_line_height', 'label' => 'H4 typography line height', 'type' => 'text', 'default' => '1.18', 'css_variable' => '--rw-public-typo-h4-line-height'],
        ['key' => 'typo_h4_letter_spacing', 'label' => 'H4 typography letter spacing', 'type' => 'text', 'default' => '-0.02em', 'css_variable' => '--rw-public-typo-h4-letter-spacing'],
        ['key' => 'typo_h5_font_family', 'label' => 'H5 typography font', 'type' => 'text', 'default' => 'var(--rw-public-font-heading)', 'css_variable' => '--rw-public-typo-h5-font-family'],
        ['key' => 'typo_h5_font_size', 'label' => 'H5 typography size', 'type' => 'text', 'default' => '1.125rem', 'css_variable' => '--rw-public-typo-h5-font-size'],
        ['key' => 'typo_h5_font_weight', 'label' => 'H5 typography weight', 'type' => 'text', 'default' => '700', 'css_variable' => '--rw-public-typo-h5-font-weight'],
        ['key' => 'typo_h5_line_height', 'label' => 'H5 typography line height', 'type' => 'text', 'default' => '1.25', 'css_variable' => '--rw-public-typo-h5-line-height'],
        ['key' => 'typo_h5_letter_spacing', 'label' => 'H5 typography letter spacing', 'type' => 'text', 'default' => '-0.01em', 'css_variable' => '--rw-public-typo-h5-letter-spacing'],
        ['key' => 'typo_h6_font_family', 'label' => 'H6 typography font', 'type' => 'text', 'default' => 'var(--rw-public-font-heading)', 'css_variable' => '--rw-public-typo-h6-font-family'],
        ['key' => 'typo_h6_font_size', 'label' => 'H6 typography size', 'type' => 'text', 'default' => '1rem', 'css_variable' => '--rw-public-typo-h6-font-size'],
        ['key' => 'typo_h6_font_weight', 'label' => 'H6 typography weight', 'type' => 'text', 'default' => '700', 'css_variable' => '--rw-public-typo-h6-font-weight'],
        ['key' => 'typo_h6_line_height', 'label' => 'H6 typography line height', 'type' => 'text', 'default' => '1.3', 'css_variable' => '--rw-public-typo-h6-line-height'],
        ['key' => 'typo_h6_letter_spacing', 'label' => 'H6 typography letter spacing', 'type' => 'text', 'default' => '0', 'css_variable' => '--rw-public-typo-h6-letter-spacing'],
        ['key' => 'typo_body_font_family', 'label' => 'Body typography font', 'type' => 'text', 'default' => 'var(--rw-public-font-body)', 'css_variable' => '--rw-public-typo-body-font-family'],
        ['key' => 'typo_body_font_size', 'label' => 'Body typography size', 'type' => 'text', 'default' => 'var(--rw-public-font-size-body)', 'css_variable' => '--rw-public-typo-body-font-size'],
        ['key' => 'typo_body_font_weight', 'label' => 'Body typography weight', 'type' => 'text', 'default' => '400', 'css_variable' => '--rw-public-typo-body-font-weight'],
        ['key' => 'typo_body_line_height', 'label' => 'Body typography line height', 'type' => 'text', 'default' => '1.7', 'css_variable' => '--rw-public-typo-body-line-height'],
        ['key' => 'typo_body_letter_spacing', 'label' => 'Body typography letter spacing', 'type' => 'text', 'default' => '0', 'css_variable' => '--rw-public-typo-body-letter-spacing'],
        ['key' => 'typo_lead_font_family', 'label' => 'Lead typography font', 'type' => 'text', 'default' => 'var(--rw-public-font-body)', 'css_variable' => '--rw-public-typo-lead-font-family'],
        ['key' => 'typo_lead_font_size', 'label' => 'Lead typography size', 'type' => 'text', 'default' => 'clamp(1.15rem, 2.2vw, 1.45rem)', 'css_variable' => '--rw-public-typo-lead-font-size'],
        ['key' => 'typo_lead_font_weight', 'label' => 'Lead typography weight', 'type' => 'text', 'default' => '500', 'css_variable' => '--rw-public-typo-lead-font-weight'],
        ['key' => 'typo_lead_line_height', 'label' => 'Lead typography line height', 'type' => 'text', 'default' => '1.65', 'css_variable' => '--rw-public-typo-lead-line-height'],
        ['key' => 'typo_lead_letter_spacing', 'label' => 'Lead typography letter spacing', 'type' => 'text', 'default' => '-0.01em', 'css_variable' => '--rw-public-typo-lead-letter-spacing'],
        ['key' => 'typo_small_font_family', 'label' => 'Small typography font', 'type' => 'text', 'default' => 'var(--rw-public-font-body)', 'css_variable' => '--rw-public-typo-small-font-family'],
        ['key' => 'typo_small_font_size', 'label' => 'Small typography size', 'type' => 'text', 'default' => 'var(--rw-public-font-size-small)', 'css_variable' => '--rw-public-typo-small-font-size'],
        ['key' => 'typo_small_font_weight', 'label' => 'Small typography weight', 'type' => 'text', 'default' => '400', 'css_variable' => '--rw-public-typo-small-font-weight'],
        ['key' => 'typo_small_line_height', 'label' => 'Small typography line height', 'type' => 'text', 'default' => '1.55', 'css_variable' => '--rw-public-typo-small-line-height'],
        ['key' => 'typo_small_letter_spacing', 'label' => 'Small typography letter spacing', 'type' => 'text', 'default' => '0', 'css_variable' => '--rw-public-typo-small-letter-spacing'],
        ['key' => 'typo_caption_font_family', 'label' => 'Caption typography font', 'type' => 'text', 'default' => 'var(--rw-public-font-body)', 'css_variable' => '--rw-public-typo-caption-font-family'],
        ['key' => 'typo_caption_font_size', 'label' => 'Caption typography size', 'type' => 'text', 'default' => '0.78rem', 'css_variable' => '--rw-public-typo-caption-font-size'],
        ['key' => 'typo_caption_font_weight', 'label' => 'Caption typography weight', 'type' => 'text', 'default' => '600', 'css_variable' => '--rw-public-typo-caption-font-weight'],
        ['key' => 'typo_caption_line_height', 'label' => 'Caption typography line height', 'type' => 'text', 'default' => '1.45', 'css_variable' => '--rw-public-typo-caption-line-height'],
        ['key' => 'typo_caption_letter_spacing', 'label' => 'Caption typography letter spacing', 'type' => 'text', 'default' => '0.02em', 'css_variable' => '--rw-public-typo-caption-letter-spacing'],
        ['key' => 'typo_eyebrow_font_family', 'label' => 'Eyebrow typography font', 'type' => 'text', 'default' => 'var(--rw-public-font-body)', 'css_variable' => '--rw-public-typo-eyebrow-font-family'],
        ['key' => 'typo_eyebrow_font_size', 'label' => 'Eyebrow typography size', 'type' => 'text', 'default' => '0.78rem', 'css_variable' => '--rw-public-typo-eyebrow-font-size'],
        ['key' => 'typo_eyebrow_font_weight', 'label' => 'Eyebrow typography weight', 'type' => 'text', 'default' => '800', 'css_variable' => '--rw-public-typo-eyebrow-font-weight'],
        ['key' => 'typo_eyebrow_line_height', 'label' => 'Eyebrow typography line height', 'type' => 'text', 'default' => '1.2', 'css_variable' => '--rw-public-typo-eyebrow-line-height'],
        ['key' => 'typo_eyebrow_letter_spacing', 'label' => 'Eyebrow typography letter spacing', 'type' => 'text', 'default' => '0.12em', 'css_variable' => '--rw-public-typo-eyebrow-letter-spacing'],
        ['key' => 'button_radius', 'label' => 'Knop radius', 'type' => 'text', 'default' => '999px', 'selector' => '.rw-public-button, .rw-public-form__submit', 'property' => 'border-radius'],
        ['key' => 'header_background', 'label' => 'Header achtergrond', 'type' => 'color', 'default' => '#ffffff', 'selector' => '.rw-public-header', 'property' => 'background'],
        ['key' => 'footer_background', 'label' => 'Footer achtergrond', 'type' => 'color', 'default' => '#ffffff', 'selector' => '.rw-public-footer', 'property' => 'background'],
    ],
];
