<?php

return [
    'contract' => [
        'version' => 1,
        'zones' => [
            'content' => ['content'],
            'layout' => ['head', 'header', 'footer', 'body_end'],
        ],
        'editor_field_types' => [
            'text',
            'url',
            'textarea',
            'rich_text',
            'markdown',
            'number',
            'checkbox',
            'select',
            'media_select',
            'media_list',
            'download_select',
            'download_list',
            'download_folder_select',
            'download_folder_list',
            'form_select',
            'menu_select',
            'code',
            'repeater',
        ],
        'categories' => ['content', 'system', 'code', 'header', 'navigation'],
        'rendering_modes' => ['safe_blade', 'platform_blade', 'raw_code_permissioned'],
        'package_field_type_mappings' => [
            'text' => 'scalar.portable',
            'url' => 'scalar.portable',
            'textarea' => 'scalar.portable',
            'rich_text' => 'scalar.portable',
            'markdown' => 'scalar.portable',
            'number' => 'scalar.portable',
            'checkbox' => 'scalar.portable',
            'select' => 'scalar.portable',
            'code' => 'scalar.portable',
            'repeater' => 'repeater',
            'media_select' => 'media.single',
            'media_list' => 'media.multiple',
            'download_select' => 'download.single',
            'download_list' => 'download.multiple',
            'download_folder_select' => 'download_folder.single',
            'download_folder_list' => 'download_folder.multiple',
            'form_select' => 'form.translation_key',
            'menu_select' => 'menu.import_key',
        ],
        'safe_blade' => [
            'enabled' => true,
            'definition_level_only' => true,
            'template_definition_field' => 'safe_blade_template',
            'runtime_view' => 'public.system.blocks.safe-blade',
            'syntax' => ['echo', 'if', 'elseif', 'else', 'endif', 'foreach', 'endforeach', 'cmsSlot', 'desktop', 'tablet', 'mobile'],
            'path_pattern' => '/^[A-Za-z0-9_]+(\.[A-Za-z0-9_]+)*$/',
            'escape_output' => true,
            'preserve_unknown_placeholders' => true,
            'forbidden' => ['php', 'blade_engine', 'method_calls', 'helpers', 'includes', 'raw_output'],
        ],
        'css' => [
            'definition_level_first' => true,
            'instance_overrides_enabled' => false,
            'supported_definition_fields' => ['style_css', 'custom_class', 'css_variables'],
        ],
        'behaviors' => [
            'allow_free_javascript' => false,
            'keys' => ['tabs', 'accordion', 'modal', 'carousel', 'sticky', 'menu', 'docs-toc'],
        ],
        'packages' => [
            'types' => ['theme-package', 'layout-template-package', 'starter-site-package'],
            'key_fields' => ['import_key', 'translation_key', 'package_key'],
            'import_mode' => 'draft_first',
        ],
    ],

    'types' => [
        'text' => [
            'label_key' => 'components.block_editor.text',
            'category' => 'content',
            'rendering_mode' => 'safe_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.text',
            'fields' => ['title', 'text'],
            'defaults' => ['title' => null, 'text' => null],
            'safe_blade_template' => '<article class="rw-public-block rw-public-block--text"><div class="rw-public-block__body">@if(block.title)<h2 class="rw-public-block__title">{{ block.title }}</h2>@endif@if(block.text)<p class="rw-public-block__text">{{ block.text }}</p>@endif</div>@cmsSlot(actions)</article>',
            'slots' => [
                [
                    'key' => 'actions',
                    'label' => 'Actions',
                    'help' => 'Links or buttons shown with this text block.',
                    'allowed_block_keys' => ['button', 'site_button', 'site_link'],
                    'min_items' => 0,
                    'max_items' => 3,
                    'layout' => 'inline',
                    'columns' => 12,
                    'responsive' => 'wrap_mobile',
                ],
            ],
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.optional_title'],
                    ['name' => 'text', 'type' => 'textarea', 'label_key' => 'components.block_editor.text', 'placeholder_key' => 'components.block_editor.text_placeholder', 'rows' => 4],
                ],
            ],
        ],
        'rich_text' => [
            'label_key' => 'components.block_editor.rich_text',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.rich-text',
            'fields' => ['title', 'html'],
            'defaults' => ['title' => null, 'html' => null],
            'slots' => [
                [
                    'key' => 'actions',
                    'label' => 'Actions',
                    'help' => 'Optional links or buttons below the rich text.',
                    'allowed_block_keys' => ['button', 'site_button', 'site_link'],
                    'min_items' => 0,
                    'max_items' => 3,
                    'layout' => 'inline',
                    'columns' => 12,
                    'responsive' => 'wrap_mobile',
                ],
            ],
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.optional_title'],
                    ['name' => 'html', 'type' => 'rich_text', 'label_key' => 'components.block_editor.rich_text_content', 'placeholder_key' => 'components.block_editor.rich_text_placeholder'],
                ],
            ],
        ],
        'markdown_text' => [
            'label_key' => 'components.block_editor.markdown_text',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.markdown-text',
            'fields' => ['title', 'markdown'],
            'defaults' => ['title' => null, 'markdown' => null],
            'slots' => [
                [
                    'key' => 'actions',
                    'label' => 'Actions',
                    'help' => 'Optional links or buttons below the markdown text.',
                    'allowed_block_keys' => ['button', 'site_button', 'site_link'],
                    'min_items' => 0,
                    'max_items' => 3,
                    'layout' => 'inline',
                    'columns' => 12,
                    'responsive' => 'wrap_mobile',
                ],
            ],
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.optional_title'],
                    ['name' => 'markdown', 'type' => 'markdown', 'label_key' => 'components.block_editor.markdown_content', 'placeholder_key' => 'components.block_editor.markdown_placeholder'],
                ],
            ],
        ],
        'feature_card' => [
            'label_key' => 'components.block_editor.feature_card',
            'category' => 'content',
            'rendering_mode' => 'safe_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.feature-card',
            'fields' => ['title', 'text'],
            'defaults' => ['title' => null, 'text' => null],
            'safe_blade_template' => '<article class="rw-public-block rw-public-block--feature-card"><div class="rw-public-feature-card__accent" aria-hidden="true"></div>@cmsSlot(media)<div class="rw-public-block__body">@if(block.title)<h2 class="rw-public-block__title rw-public-feature-card__title">{{ block.title }}</h2>@endif@if(block.text)<p class="rw-public-block__text rw-public-feature-card__text">{{ block.text }}</p>@endif</div>@cmsSlot(actions)</article>',
            'slots' => [
                [
                    'key' => 'media',
                    'label' => 'Media',
                    'help' => 'Optional image shown inside the feature card.',
                    'allowed_block_keys' => ['image'],
                    'min_items' => 0,
                    'max_items' => 1,
                    'layout' => 'stack',
                    'columns' => 12,
                    'responsive' => 'same',
                ],
                [
                    'key' => 'actions',
                    'label' => 'Actions',
                    'help' => 'Buttons shown below the feature card content.',
                    'allowed_block_keys' => ['button', 'site_button', 'site_link'],
                    'min_items' => 0,
                    'max_items' => 2,
                    'layout' => 'inline',
                    'columns' => 12,
                    'responsive' => 'wrap_mobile',
                ],
            ],
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.optional_title'],
                    ['name' => 'text', 'type' => 'textarea', 'label_key' => 'components.block_editor.text', 'placeholder_key' => 'components.block_editor.text_placeholder', 'rows' => 4],
                ],
            ],
        ],
        'quote' => [
            'label_key' => 'components.block_editor.quote',
            'category' => 'content',
            'rendering_mode' => 'safe_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.quote',
            'fields' => ['text', 'source'],
            'defaults' => ['text' => null, 'source' => null],
            'safe_blade_template' => '<article class="rw-public-block rw-public-block--quote"><blockquote class="rw-public-quote"><p class="rw-public-quote__text">{{ block.text }}</p>@if(block.source)<footer class="rw-public-quote__source">{{ block.source }}</footer>@endif</blockquote>@cmsSlot(actions)</article>',
            'slots' => [
                [
                    'key' => 'actions',
                    'label' => 'Actions',
                    'help' => 'Optional links or buttons below the quote.',
                    'allowed_block_keys' => ['button', 'site_button', 'site_link'],
                    'min_items' => 0,
                    'max_items' => 2,
                    'layout' => 'inline',
                    'columns' => 12,
                    'responsive' => 'wrap_mobile',
                ],
            ],
            'preview' => ['title_field' => 'text'],
            'editor' => [
                'fields' => [
                    ['name' => 'text', 'type' => 'textarea', 'label_key' => 'components.block_editor.quote', 'placeholder_key' => 'components.block_editor.quote_placeholder', 'rows' => 3],
                    ['name' => 'source', 'type' => 'text', 'label_key' => 'components.block_editor.source', 'placeholder_key' => 'components.block_editor.optional_source'],
                ],
            ],
        ],
        'testimonial' => [
            'label_key' => 'components.block_editor.testimonial',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.testimonial',
            'fields' => ['text', 'source'],
            'defaults' => ['text' => null, 'source' => null],
            'slots' => [
                [
                    'key' => 'actions',
                    'label' => 'Actions',
                    'help' => 'Optional links or buttons below the testimonial.',
                    'allowed_block_keys' => ['button', 'site_button', 'site_link'],
                    'min_items' => 0,
                    'max_items' => 2,
                    'layout' => 'inline',
                    'columns' => 12,
                    'responsive' => 'wrap_mobile',
                ],
            ],
            'preview' => ['title_field' => 'source'],
            'editor' => [
                'fields' => [
                    ['name' => 'text', 'type' => 'textarea', 'label_key' => 'components.block_editor.testimonial', 'placeholder_key' => 'components.block_editor.quote_placeholder', 'rows' => 3],
                    ['name' => 'source', 'type' => 'text', 'label_key' => 'components.block_editor.source', 'placeholder_key' => 'components.block_editor.optional_source'],
                ],
            ],
        ],
        'stats' => [
            'label_key' => 'components.block_editor.stats',
            'category' => 'content',
            'rendering_mode' => 'safe_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.stats',
            'fields' => ['value', 'suffix', 'label'],
            'defaults' => ['value' => null, 'suffix' => null, 'label' => null],
            'safe_blade_template' => '<article class="rw-public-block rw-public-block--stats">@if(block.value)<p class="rw-public-stats__value"><span>{{ block.value }}</span>@if(block.suffix)<span class="rw-public-stats__suffix">{{ block.suffix }}</span>@endif</p>@elseif(block.suffix)<p class="rw-public-stats__value"><span class="rw-public-stats__suffix">{{ block.suffix }}</span></p>@endif@if(block.label)<p class="rw-public-stats__label">{{ block.label }}</p>@endif</article>',
            'preview' => ['title_field' => 'label'],
            'editor' => [
                'fields' => [
                    ['name' => 'value', 'type' => 'text', 'label_key' => 'components.block_editor.stats_value', 'placeholder_key' => 'components.block_editor.stats_value_placeholder'],
                    ['name' => 'suffix', 'type' => 'text', 'label_key' => 'components.block_editor.stats_suffix', 'placeholder_key' => 'components.block_editor.optional_stats_suffix'],
                    ['name' => 'label', 'type' => 'text', 'label_key' => 'components.block_editor.stats_label', 'placeholder_key' => 'components.block_editor.stats_label_placeholder'],
                ],
            ],
        ],
        'accordion' => [
            'label_key' => 'components.block_editor.accordion',
            'category' => 'content',
            'rendering_mode' => 'safe_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.text',
            'fields' => ['items'],
            'defaults' => ['items' => []],
            'behavior_key' => 'accordion',
            'safe_blade_template' => '<article class="rw-public-block rw-public-block--accordion">@foreach(block.items as item)@if(item.title)<button type="button" class="rw-public-accordion__trigger" data-cms-accordion-trigger aria-expanded="false" aria-controls="accordion-panel-{{ item.runtime_id }}">{{ item.title }}</button><div id="accordion-panel-{{ item.runtime_id }}" class="rw-public-accordion__panel" hidden>@if(item.text)<p class="rw-public-block__text">{{ item.text }}</p>@endif</div>@endif@endforeach</article>',
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'items', 'type' => 'repeater', 'label_key' => 'components.block_editor.accordion_items', 'fields' => [
                        ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.accordion_title', 'placeholder_key' => 'components.block_editor.accordion_title_placeholder'],
                        ['name' => 'text', 'type' => 'textarea', 'label_key' => 'components.block_editor.accordion_content', 'placeholder_key' => 'components.block_editor.accordion_content_placeholder', 'rows' => 4],
                    ]],
                ],
            ],
        ],
        'tabs' => [
            'label_key' => 'components.block_editor.tabs',
            'category' => 'content',
            'rendering_mode' => 'safe_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.text',
            'fields' => ['items'],
            'defaults' => ['items' => []],
            'behavior_key' => 'tabs',
            'safe_blade_template' => '<article class="rw-public-block rw-public-block--tabs"><div class="rw-public-tabs__list" role="tablist">@foreach(block.items as item)@if(item.title)<button type="button" role="tab" id="tabs-tab-{{ item.runtime_id }}" aria-controls="tabs-panel-{{ item.runtime_id }}" aria-selected="@if(item.is_first)true@elsefalse@endif" tabindex="@if(item.is_first)0@else-1@endif">{{ item.title }}</button>@endif@endforeach</div>@foreach(block.items as item)@if(item.title)<section id="tabs-panel-{{ item.runtime_id }}" role="tabpanel" aria-labelledby="tabs-tab-{{ item.runtime_id }}" @if(item.is_first)@else hidden@endif>@if(item.text)<p class="rw-public-block__text">{{ item.text }}</p>@endif</section>@endif@endforeach</article>',
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'items', 'type' => 'repeater', 'label_key' => 'components.block_editor.tabs', 'fields' => [
                        ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.tab_title_placeholder'],
                        ['name' => 'text', 'type' => 'textarea', 'label_key' => 'components.block_editor.text', 'placeholder_key' => 'components.block_editor.tab_content_placeholder', 'rows' => 3],
                    ]],
                ],
            ],
        ],
        'carousel' => [
            'label_key' => 'components.block_editor.carousel',
            'category' => 'content',
            'rendering_mode' => 'safe_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.text',
            'fields' => ['items', 'previous_label', 'next_label'],
            'defaults' => ['items' => [], 'previous_label' => null, 'next_label' => null],
            'behavior_key' => 'carousel',
            'safe_blade_template' => '<article class="rw-public-block rw-public-block--carousel">@foreach(block.items as item)@if(item.title)<section id="carousel-slide-{{ item.runtime_id }}" class="rw-public-carousel__slide" data-cms-carousel-slide @if(item.is_first)@else hidden@endif>@if(item.title)<h2 class="rw-public-block__title">{{ item.title }}</h2>@endif@if(item.text)<p class="rw-public-block__text">{{ item.text }}</p>@endif</section>@endif@endforeach@if(block.previous_label)<button type="button" class="rw-public-carousel__previous" data-cms-carousel-prev>{{ block.previous_label }}</button>@endif@if(block.next_label)<button type="button" class="rw-public-carousel__next" data-cms-carousel-next>{{ block.next_label }}</button>@endif</article>',
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'items', 'type' => 'repeater', 'label_key' => 'components.block_editor.carousel', 'fields' => [
                        ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.slide_title_placeholder'],
                        ['name' => 'text', 'type' => 'textarea', 'label_key' => 'components.block_editor.text', 'placeholder_key' => 'components.block_editor.slide_content_placeholder', 'rows' => 3],
                    ]],
                    ['name' => 'previous_label', 'type' => 'text', 'label_key' => 'components.block_editor.previous_label', 'placeholder_key' => 'components.block_editor.previous_label_placeholder'],
                    ['name' => 'next_label', 'type' => 'text', 'label_key' => 'components.block_editor.next_label', 'placeholder_key' => 'components.block_editor.next_label_placeholder'],
                ],
            ],
        ],
        'faq' => [
            'label_key' => 'components.block_editor.faq',
            'category' => 'content',
            'rendering_mode' => 'safe_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.text',
            'fields' => ['items'],
            'defaults' => ['items' => []],
            'behavior_key' => 'accordion',
            'safe_blade_template' => '<article class="rw-public-block rw-public-block--faq">@foreach(block.items as item)@if(item.question)<button type="button" class="rw-public-accordion__trigger" data-cms-accordion-trigger aria-expanded="false" aria-controls="faq-panel-{{ item.runtime_id }}">{{ item.question }}</button><div id="faq-panel-{{ item.runtime_id }}" class="rw-public-accordion__panel" hidden>@if(item.answer)<p class="rw-public-block__text">{{ item.answer }}</p>@endif</div>@endif@endforeach</article>',
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'items', 'type' => 'repeater', 'label_key' => 'components.block_editor.faq', 'fields' => [
                        ['name' => 'question', 'type' => 'text', 'label_key' => 'components.block_editor.question', 'placeholder_key' => 'components.block_editor.question_placeholder'],
                        ['name' => 'answer', 'type' => 'textarea', 'label_key' => 'components.block_editor.answer', 'placeholder_key' => 'components.block_editor.answer_placeholder', 'rows' => 4],
                    ]],
                ],
            ],
        ],
        'steps' => [
            'label_key' => 'components.block_editor.steps',
            'category' => 'content',
            'rendering_mode' => 'safe_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.text',
            'fields' => ['items'],
            'defaults' => ['items' => []],
            'safe_blade_template' => '<article class="rw-public-block rw-public-block--steps"><ol class="rw-public-steps">@foreach(block.items as item)@if(item.title)<li class="rw-public-steps__item">@if(item.title)<h2 class="rw-public-block__title">{{ item.title }}</h2>@endif@if(item.text)<p class="rw-public-block__text">{{ item.text }}</p>@endif</li>@endif@endforeach</ol></article>',
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'items', 'type' => 'repeater', 'label_key' => 'components.block_editor.steps', 'fields' => [
                        ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.optional_title'],
                        ['name' => 'text', 'type' => 'textarea', 'label_key' => 'components.block_editor.text', 'placeholder_key' => 'components.block_editor.text_placeholder', 'rows' => 3],
                    ]],
                ],
            ],
        ],
        'icon_list' => [
            'label_key' => 'components.block_editor.icon_list',
            'category' => 'content',
            'rendering_mode' => 'safe_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.text',
            'fields' => ['items'],
            'defaults' => ['items' => []],
            'safe_blade_template' => '<article class="rw-public-block rw-public-block--icon-list"><ul class="rw-public-icon-list">@foreach(block.items as item)@if(item.title)<li class="rw-public-icon-list__item"><span class="rw-public-icon-list__marker" aria-hidden="true"></span><span>@if(item.title)<strong>{{ item.title }}</strong>@endif@if(item.text)<span class="rw-public-block__text">{{ item.text }}</span>@endif</span></li>@endif@endforeach</ul></article>',
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'items', 'type' => 'repeater', 'label_key' => 'components.block_editor.icon_list', 'fields' => [
                        ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.optional_title'],
                        ['name' => 'text', 'type' => 'textarea', 'label_key' => 'components.block_editor.text', 'placeholder_key' => 'components.block_editor.text_placeholder', 'rows' => 2],
                    ]],
                ],
            ],
        ],
        'video' => [
            'label_key' => 'components.block_editor.video',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.video',
            'fields' => ['title', 'video_url'],
            'defaults' => ['title' => null, 'video_url' => null],
            'slots' => [
                [
                    'key' => 'actions',
                    'label' => 'Actions',
                    'help' => 'Optional links or buttons shown below the video.',
                    'allowed_block_keys' => ['button', 'site_button', 'site_link'],
                    'min_items' => 0,
                    'max_items' => 2,
                    'layout' => 'inline',
                    'columns' => 12,
                    'responsive' => 'wrap_mobile',
                ],
            ],
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.optional_title'],
                    ['name' => 'video_url', 'type' => 'url', 'label_key' => 'components.block_editor.video_url', 'placeholder_key' => 'components.block_editor.video_url_placeholder'],
                ],
            ],
        ],
        'logo_strip' => [
            'label_key' => 'components.block_editor.logo_strip',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.logo-strip',
            'fields' => ['title', 'media_asset_ids'],
            'defaults' => ['title' => null, 'media_asset_ids' => []],
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.optional_title'],
                    ['name' => 'media_asset_ids', 'type' => 'media_list', 'label_key' => 'components.block_editor.logo_images'],
                ],
            ],
        ],
        'button' => [
            'label_key' => 'components.block_editor.button',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.button',
            'fields' => ['label', 'url', 'open_in_new_tab'],
            'defaults' => ['label' => null, 'url' => null, 'open_in_new_tab' => false],
            'preview' => ['title_field' => 'label'],
            'editor' => [
                'fields' => [
                    ['name' => 'label', 'type' => 'text', 'label_key' => 'components.block_editor.label', 'placeholder_key' => 'components.block_editor.button_label_placeholder', 'required' => true],
                    ['name' => 'url', 'type' => 'url', 'label_key' => 'components.block_editor.url', 'placeholder_key' => 'components.block_editor.url_placeholder', 'required' => true],
                    ['name' => 'open_in_new_tab', 'type' => 'checkbox', 'label_key' => 'components.block_editor.open_in_new_tab'],
                ],
            ],
        ],
        'image' => [
            'label_key' => 'components.block_editor.image',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.image',
            'fields' => ['media_asset_id', 'caption'],
            'defaults' => ['media_asset_id' => null, 'caption' => null],
            'preview' => ['title_field' => 'caption'],
            'editor' => [
                'fields' => [
                    ['name' => 'media_asset_id', 'type' => 'media_select', 'label_key' => 'components.block_editor.image'],
                    ['name' => 'caption', 'type' => 'text', 'label_key' => 'components.block_editor.caption', 'placeholder_key' => 'components.block_editor.optional_caption'],
                ],
            ],
        ],
        'download_list' => [
            'label_key' => 'components.block_editor.download_list',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.download-list',
            'fields' => ['title', 'source_mode', 'download_asset_ids', 'folder_ids', 'include_subfolders', 'show_descriptions'],
            'defaults' => [
                'title' => null,
                'source_mode' => 'folders',
                'download_asset_ids' => [],
                'folder_ids' => [],
                'include_subfolders' => true,
                'show_descriptions' => true,
            ],
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.optional_title'],
                    ['name' => 'source_mode', 'type' => 'select', 'label_key' => 'components.block_editor.download_source_mode', 'options' => [
                        ['value' => 'folders', 'label_key' => 'components.block_editor.download_source_folders'],
                        ['value' => 'manual', 'label_key' => 'components.block_editor.download_source_manual'],
                        ['value' => 'allowed_for_current_user', 'label_key' => 'components.block_editor.download_source_allowed_user'],
                    ]],
                    ['name' => 'download_asset_ids', 'type' => 'download_list', 'label_key' => 'components.block_editor.downloads'],
                    ['name' => 'folder_ids', 'type' => 'download_folder_list', 'label_key' => 'components.block_editor.download_folders'],
                    ['name' => 'include_subfolders', 'type' => 'checkbox', 'label_key' => 'components.block_editor.include_subfolders'],
                    ['name' => 'show_descriptions', 'type' => 'checkbox', 'label_key' => 'components.block_editor.show_descriptions'],
                ],
            ],
        ],
        'download_browser' => [
            'label_key' => 'components.block_editor.download_browser',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.download-browser',
            'fields' => ['title', 'folder_ids', 'include_subfolders', 'show_descriptions'],
            'defaults' => ['title' => null, 'folder_ids' => [], 'include_subfolders' => true, 'show_descriptions' => true],
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.optional_title'],
                    ['name' => 'folder_ids', 'type' => 'download_folder_list', 'label_key' => 'components.block_editor.download_folders'],
                    ['name' => 'include_subfolders', 'type' => 'checkbox', 'label_key' => 'components.block_editor.include_subfolders'],
                    ['name' => 'show_descriptions', 'type' => 'checkbox', 'label_key' => 'components.block_editor.show_descriptions'],
                ],
            ],
        ],
        'address_block' => [
            'label_key' => 'components.block_editor.address_block',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.address-block',
            'fields' => [
                'title',
                'media_asset_id',
                'image_position',
                'show_company_name',
                'company_name',
                'show_address',
                'street',
                'postal_code',
                'city',
                'country',
                'country_code',
                'show_phones',
                'phone_1_label',
                'phone_1',
                'phone_2_label',
                'phone_2',
                'phone_3_label',
                'phone_3',
                'show_emails',
                'email_1_label',
                'email_1',
                'email_2_label',
                'email_2',
                'show_vat_number',
                'vat_number',
                'show_custom_fields',
                'custom_field_1_label',
                'custom_field_1_value',
                'custom_field_2_label',
                'custom_field_2_value',
                'custom_field_3_label',
                'custom_field_3_value',
            ],
            'defaults' => [
                'title' => null,
                'media_asset_id' => null,
                'image_position' => 'top',
                'show_company_name' => true,
                'company_name' => null,
                'show_address' => true,
                'street' => null,
                'postal_code' => null,
                'city' => null,
                'country' => null,
                'country_code' => null,
                'show_phones' => true,
                'phone_1_label' => null,
                'phone_1' => null,
                'phone_2_label' => null,
                'phone_2' => null,
                'phone_3_label' => null,
                'phone_3' => null,
                'show_emails' => true,
                'email_1_label' => null,
                'email_1' => null,
                'email_2_label' => null,
                'email_2' => null,
                'show_vat_number' => true,
                'vat_number' => null,
                'show_custom_fields' => true,
                'custom_field_1_label' => null,
                'custom_field_1_value' => null,
                'custom_field_2_label' => null,
                'custom_field_2_value' => null,
                'custom_field_3_label' => null,
                'custom_field_3_value' => null,
            ],
            'slots' => [
                [
                    'key' => 'actions',
                    'label' => 'Actions',
                    'help' => 'Optional links or buttons below the contact details.',
                    'allowed_block_keys' => ['button', 'site_button', 'site_link'],
                    'min_items' => 0,
                    'max_items' => 3,
                    'layout' => 'inline',
                    'columns' => 12,
                    'responsive' => 'wrap_mobile',
                ],
            ],
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.optional_title', 'placeholder_key' => 'components.block_editor.optional_title'],
                    ['name' => 'media_asset_id', 'type' => 'media_select', 'label_key' => 'components.block_editor.address_image'],
                    ['name' => 'image_position', 'type' => 'select', 'label_key' => 'components.block_editor.address_image_position', 'options' => [
                        ['value' => 'top', 'label_key' => 'components.block_editor.address_image_position_top'],
                        ['value' => 'left', 'label_key' => 'components.block_editor.address_image_position_left'],
                        ['value' => 'right', 'label_key' => 'components.block_editor.address_image_position_right'],
                        ['value' => 'bottom', 'label_key' => 'components.block_editor.address_image_position_bottom'],
                    ]],
                    ['name' => 'show_company_name', 'type' => 'checkbox', 'label_key' => 'components.block_editor.address_show_company_name'],
                    ['name' => 'company_name', 'type' => 'text', 'label_key' => 'components.block_editor.company_name', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'show_address', 'type' => 'checkbox', 'label_key' => 'components.block_editor.address_show_address'],
                    ['name' => 'street', 'type' => 'text', 'label_key' => 'components.block_editor.address_street', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'postal_code', 'type' => 'text', 'label_key' => 'components.block_editor.address_postal_code', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'city', 'type' => 'text', 'label_key' => 'components.block_editor.address_city', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'country', 'type' => 'text', 'label_key' => 'components.block_editor.address_country', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'country_code', 'type' => 'text', 'label_key' => 'components.block_editor.address_country_code', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'show_phones', 'type' => 'checkbox', 'label_key' => 'components.block_editor.address_show_phones'],
                    ['name' => 'phone_1_label', 'type' => 'text', 'label_key' => 'components.block_editor.address_phone_1_label', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'phone_1', 'type' => 'text', 'label_key' => 'components.block_editor.address_phone_1', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'phone_2_label', 'type' => 'text', 'label_key' => 'components.block_editor.address_phone_2_label', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'phone_2', 'type' => 'text', 'label_key' => 'components.block_editor.address_phone_2', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'phone_3_label', 'type' => 'text', 'label_key' => 'components.block_editor.address_phone_3_label', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'phone_3', 'type' => 'text', 'label_key' => 'components.block_editor.address_phone_3', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'show_emails', 'type' => 'checkbox', 'label_key' => 'components.block_editor.address_show_emails'],
                    ['name' => 'email_1_label', 'type' => 'text', 'label_key' => 'components.block_editor.address_email_1_label', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'email_1', 'type' => 'text', 'label_key' => 'components.block_editor.address_email_1', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'email_2_label', 'type' => 'text', 'label_key' => 'components.block_editor.address_email_2_label', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'email_2', 'type' => 'text', 'label_key' => 'components.block_editor.address_email_2', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'show_vat_number', 'type' => 'checkbox', 'label_key' => 'components.block_editor.address_show_vat_number'],
                    ['name' => 'vat_number', 'type' => 'text', 'label_key' => 'components.block_editor.address_vat_number', 'placeholder_key' => 'components.block_editor.address_empty_hides_value'],
                    ['name' => 'show_custom_fields', 'type' => 'checkbox', 'label_key' => 'components.block_editor.address_show_custom_fields'],
                    ['name' => 'custom_field_1_label', 'type' => 'text', 'label_key' => 'components.block_editor.address_custom_field_1_label'],
                    ['name' => 'custom_field_1_value', 'type' => 'text', 'label_key' => 'components.block_editor.address_custom_field_1_value'],
                    ['name' => 'custom_field_2_label', 'type' => 'text', 'label_key' => 'components.block_editor.address_custom_field_2_label'],
                    ['name' => 'custom_field_2_value', 'type' => 'text', 'label_key' => 'components.block_editor.address_custom_field_2_value'],
                    ['name' => 'custom_field_3_label', 'type' => 'text', 'label_key' => 'components.block_editor.address_custom_field_3_label'],
                    ['name' => 'custom_field_3_value', 'type' => 'text', 'label_key' => 'components.block_editor.address_custom_field_3_value'],
                ],
            ],
        ],
        'form' => [
            'label_key' => 'components.block_editor.form',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.form',
            'fields' => ['form_key'],
            'defaults' => ['form_key' => null],
            'preview' => ['title_field' => 'form_key'],
            'editor' => [
                'fields' => [
                    ['name' => 'form_key', 'type' => 'form_select', 'label_key' => 'components.block_editor.form'],
                ],
            ],
        ],
        'breadcrumb' => [
            'label_key' => 'components.block_editor.breadcrumb',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.breadcrumb',
            'fields' => ['show_current', 'show_on_home', 'compact', 'home_icon', 'separator'],
            'defaults' => ['show_current' => true, 'show_on_home' => true, 'compact' => false, 'home_icon' => 'mdi-home', 'separator' => '›'],
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'show_current', 'type' => 'checkbox', 'label_key' => 'components.block_editor.show_current_page'],
                    ['name' => 'show_on_home', 'type' => 'checkbox', 'label_key' => 'components.block_editor.show_on_home'],
                    ['name' => 'compact', 'type' => 'checkbox', 'label_key' => 'components.block_editor.compact_display'],
                    ['name' => 'home_icon', 'type' => 'text', 'label_key' => 'components.block_editor.home_icon', 'placeholder_key' => 'components.block_editor.home_icon_placeholder'],
                    ['name' => 'separator', 'type' => 'select', 'label_key' => 'components.block_editor.breadcrumb_separator', 'options' => [
                        ['value' => '›', 'label_key' => 'components.block_editor.separator_chevron', 'label' => '›'],
                        ['value' => '>', 'label_key' => 'components.block_editor.separator_greater_than', 'label' => '>'],
                        ['value' => '/', 'label_key' => 'components.block_editor.separator_slash', 'label' => '/'],
                        ['value' => '•', 'label_key' => 'components.block_editor.separator_dot', 'label' => '•'],
                    ]],
                ],
            ],
        ],
        'list_rows' => [
            'label_key' => 'components.block_editor.list_rows',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.content-list',
            'fields' => ['title', 'source_type', 'category_source', 'category_id', 'tag_source', 'tag_id', 'show_only_subcategories', 'limit', 'sort_field', 'sort_direction', 'show_search', 'show_excerpt', 'show_image', 'show_date', 'show_categories', 'empty_text'],
            'package_mappings' => ['category_id' => 'category.import_key', 'tag_id' => 'tag.import_key'],
            'defaults' => [
                'title' => null,
                'source_type' => 'category',
                'category_source' => 'all',
                'category_id' => null,
                'tag_source' => 'all',
                'tag_id' => null,
                'show_only_subcategories' => false,
                'limit' => 24,
                'sort_field' => 'published_at',
                'sort_direction' => 'desc',
                'show_search' => false,
                'show_excerpt' => true,
                'show_image' => true,
                'show_date' => true,
                'show_categories' => true,
                'empty_text' => null,
            ],
            'slots' => [
                [
                    'key' => 'actions',
                    'label' => 'Actions',
                    'help' => 'Optional links or buttons shown with the content list.',
                    'allowed_block_keys' => ['button', 'site_button', 'site_link'],
                    'min_items' => 0,
                    'max_items' => 2,
                    'layout' => 'inline',
                    'columns' => 12,
                    'responsive' => 'wrap_mobile',
                ],
            ],
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.optional_list_title'],
                    ['name' => 'limit', 'type' => 'number', 'label_key' => 'components.block_editor.limit', 'min' => 1, 'max' => 100],
                    ['name' => 'show_search', 'type' => 'checkbox', 'label_key' => 'components.block_editor.show_search'],
                ],
            ],
        ],
        'list_grid' => [
            'label_key' => 'components.block_editor.list_grid',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.content-list',
            'fields' => ['title', 'source_type', 'category_source', 'category_id', 'tag_source', 'tag_id', 'show_only_subcategories', 'limit', 'sort_field', 'sort_direction', 'show_search', 'show_excerpt', 'show_image', 'show_date', 'show_categories', 'empty_text'],
            'package_mappings' => ['category_id' => 'category.import_key', 'tag_id' => 'tag.import_key'],
            'defaults' => [
                'title' => null,
                'source_type' => 'category',
                'category_source' => 'all',
                'category_id' => null,
                'tag_source' => 'all',
                'tag_id' => null,
                'show_only_subcategories' => false,
                'limit' => 24,
                'sort_field' => 'published_at',
                'sort_direction' => 'desc',
                'show_search' => false,
                'show_excerpt' => true,
                'show_image' => true,
                'show_date' => true,
                'show_categories' => true,
                'empty_text' => null,
            ],
            'slots' => [
                [
                    'key' => 'actions',
                    'label' => 'Actions',
                    'help' => 'Optional links or buttons shown with the content grid.',
                    'allowed_block_keys' => ['button', 'site_button', 'site_link'],
                    'min_items' => 0,
                    'max_items' => 2,
                    'layout' => 'inline',
                    'columns' => 12,
                    'responsive' => 'wrap_mobile',
                ],
            ],
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.title', 'placeholder_key' => 'components.block_editor.optional_list_title'],
                    ['name' => 'limit', 'type' => 'number', 'label_key' => 'components.block_editor.limit', 'min' => 1, 'max' => 100],
                    ['name' => 'show_search', 'type' => 'checkbox', 'label_key' => 'components.block_editor.show_search'],
                ],
            ],
        ],
        'dynamic_field' => [
            'label_key' => 'components.block_editor.dynamic_field',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.dynamic-field',
            'fields' => ['field_key', 'title', 'heading_level'],
            'defaults' => ['field_key' => null, 'title' => null, 'heading_level' => 'none'],
            'preview' => ['title_field' => 'field_key'],
            'editor' => [
                'fields' => [
                    ['name' => 'field_key', 'type' => 'select', 'label_key' => 'components.block_editor.field_key', 'options' => []],
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.optional_title', 'placeholder_key' => 'components.block_editor.optional_title'],
                    ['name' => 'heading_level', 'type' => 'select', 'label_key' => 'components.block_editor.heading_level', 'options' => [
                        ['value' => 'none', 'label_key' => 'components.block_editor.heading_none', 'label' => 'Geen'],
                        ['value' => 'h1', 'label' => 'H1'],
                        ['value' => 'h2', 'label' => 'H2'],
                        ['value' => 'h3', 'label' => 'H3'],
                    ]],
                ],
            ],
        ],
        'content_slot' => [
            'label_key' => 'components.block_editor.content_slot',
            'category' => 'content',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.content-slot',
            'fields' => ['slot_key', 'title'],
            'defaults' => ['slot_key' => 'content', 'title' => null],
            'preview' => ['title_field' => 'slot_key'],
            'editor' => [
                'fields' => [
                    ['name' => 'slot_key', 'type' => 'select', 'label_key' => 'components.block_editor.content_slot', 'options' => [
                        ['value' => 'content', 'label_key' => 'components.block_editor.content_slot_main', 'label' => 'Content'],
                        ['value' => 'before_list', 'label_key' => 'components.block_editor.content_slot_before_list', 'label' => 'Voor lijst'],
                        ['value' => 'after_list', 'label_key' => 'components.block_editor.content_slot_after_list', 'label' => 'Na lijst'],
                    ]],
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.optional_title', 'placeholder_key' => 'components.block_editor.optional_title'],
                ],
            ],
        ],
        'docs_mobile_actions' => [
            'label_key' => 'components.block_editor.docs_mobile_actions',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.docs-mobile-actions',
            'fields' => [],
            'defaults' => [],
            'custom_class' => 'rw-public-content-block--docs-mobile-actions',
            'preview' => ['title_field' => null],
        ],
        'docs_navigation' => [
            'label_key' => 'components.block_editor.docs_navigation',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.docs-navigation',
            'fields' => [],
            'defaults' => [],
            'custom_class' => 'rw-public-content-block--docs-navigation',
            'preview' => ['title_field' => null],
        ],
        'docs_content' => [
            'label_key' => 'components.block_editor.docs_content',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.docs-content',
            'fields' => [],
            'defaults' => [],
            'custom_class' => 'rw-public-content-block--docs-content',
            'preview' => ['title_field' => null],
        ],
        'docs_page_toc' => [
            'label_key' => 'components.block_editor.docs_page_toc',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.docs-page-toc',
            'fields' => [],
            'defaults' => [],
            'custom_class' => 'rw-public-content-block--docs-page-toc',
            'behavior_key' => 'docs-toc',
            'preview' => ['title_field' => null],
        ],
        'site_search' => [
            'label_key' => 'components.block_editor.site_search',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.site-search',
            'fields' => ['title', 'placeholder', 'button_label'],
            'defaults' => ['title' => null, 'placeholder' => null, 'button_label' => null],
            'custom_class' => 'rw-public-content-block--site-search',
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.optional_title', 'placeholder_key' => 'components.block_editor.optional_title'],
                    ['name' => 'placeholder', 'type' => 'text', 'label_key' => 'components.block_editor.search_placeholder', 'placeholder_key' => 'components.block_editor.search_placeholder_default'],
                    ['name' => 'button_label', 'type' => 'text', 'label_key' => 'components.block_editor.button_label', 'placeholder_key' => 'components.block_editor.search_button_default'],
                ],
            ],
        ],
        'docs_search' => [
            'label_key' => 'components.block_editor.docs_search',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.docs-search',
            'fields' => ['title', 'placeholder', 'button_label'],
            'defaults' => ['title' => null, 'placeholder' => null, 'button_label' => null],
            'custom_class' => 'rw-public-content-block--docs-search',
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.optional_title', 'placeholder_key' => 'components.block_editor.optional_title'],
                    ['name' => 'placeholder', 'type' => 'text', 'label_key' => 'components.block_editor.search_placeholder', 'placeholder_key' => 'components.block_editor.docs_search_placeholder_default'],
                    ['name' => 'button_label', 'type' => 'text', 'label_key' => 'components.block_editor.button_label', 'placeholder_key' => 'components.block_editor.search_button_default'],
                ],
            ],
        ],
        'site_head' => [
            'label_key' => 'layouts.sections.site_head',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['head'],
            'view' => 'public.system.blocks.site-head',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
        ],
        'site_head_meta' => [
            'label_key' => 'layouts.sections.site_head_meta',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['head'],
            'view' => 'public.system.blocks.head-meta',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
        ],
        'site_head_favicons' => [
            'label_key' => 'layouts.sections.site_head_favicons',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['head'],
            'view' => 'public.system.blocks.head-favicons',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
        ],
        'site_head_system_assets' => [
            'label_key' => 'layouts.sections.site_head_system_assets',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['head'],
            'view' => 'public.system.blocks.head-system-assets',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
        ],
        'site_head_theme' => [
            'label_key' => 'layouts.sections.site_head_theme',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['head'],
            'view' => 'public.system.blocks.head-theme',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
        ],
        'site_logo' => [
            'label_key' => 'components.block_editor.site_logo',
            'category' => 'header',
            'rendering_mode' => 'safe_blade',
            'zones' => ['header', 'footer'],
            'view' => 'public.system.blocks.site-logo',
            'fields' => ['media_asset_id', 'alt_text', 'link_url', 'open_in_new_tab'],
            'defaults' => ['media_asset_id' => null, 'alt_text' => null, 'link_url' => '/', 'open_in_new_tab' => false],
            'safe_blade_template' => '<a class="rw-public-logo" href="{{ block.link_url }}" target="{{ block.target }}" rel="{{ block.rel }}">@if(block.media.url)<img src="{{ block.media.url }}" alt="{{ block.alt_text }}">@else<span>{{ block.alt_text }}</span>@endif</a>',
            'preview' => ['title_field' => 'alt_text'],
            'editor' => [
                'fields' => [
                    ['name' => 'media_asset_id', 'type' => 'media_select', 'label_key' => 'components.block_editor.image'],
                    ['name' => 'alt_text', 'type' => 'text', 'label_key' => 'components.block_editor.alt_text', 'placeholder_key' => 'components.block_editor.alt_text_placeholder'],
                    ['name' => 'link_url', 'type' => 'url', 'label_key' => 'components.block_editor.link_url', 'placeholder_key' => 'components.block_editor.link_url_placeholder'],
                    ['name' => 'open_in_new_tab', 'type' => 'checkbox', 'label_key' => 'components.block_editor.open_in_new_tab'],
                ],
            ],
        ],
        'site_brand' => [
            'label_key' => 'components.block_editor.site_brand',
            'category' => 'header',
            'rendering_mode' => 'safe_blade',
            'zones' => ['header', 'footer', 'content'],
            'view' => 'public.system.blocks.safe-blade',
            'fields' => ['title', 'link_url', 'open_in_new_tab'],
            'defaults' => ['title' => null, 'link_url' => '/', 'open_in_new_tab' => false],
            'safe_blade_template' => '@if(block.title)<a class="rw-public-brand" href="{{ block.link_url }}" target="{{ block.target }}" rel="{{ block.rel }}"><span class="rw-public-brand__name">{{ block.title }}</span></a>@endif',
            'preview' => ['title_field' => 'title'],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.company_name', 'placeholder_key' => 'components.block_editor.company_name_placeholder'],
                    ['name' => 'link_url', 'type' => 'url', 'label_key' => 'components.block_editor.link_url', 'placeholder_key' => 'components.block_editor.link_url_placeholder'],
                    ['name' => 'open_in_new_tab', 'type' => 'checkbox', 'label_key' => 'components.block_editor.open_in_new_tab'],
                ],
            ],
        ],
        'site_baseline' => [
            'label_key' => 'components.block_editor.site_baseline',
            'category' => 'header',
            'rendering_mode' => 'safe_blade',
            'zones' => ['header', 'footer'],
            'view' => 'public.system.blocks.site-baseline',
            'fields' => ['text'],
            'defaults' => ['text' => null],
            'safe_blade_template' => '@if(block.text)<p class="rw-public-baseline">{{ block.text }}</p>@endif',
            'preview' => ['title_field' => 'text'],
            'editor' => [
                'fields' => [
                    ['name' => 'text', 'type' => 'text', 'label_key' => 'components.block_editor.baseline', 'placeholder_key' => 'components.block_editor.baseline_placeholder'],
                ],
            ],
        ],
        'site_menu' => [
            'label_key' => 'components.block_editor.site_menu',
            'category' => 'navigation',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content', 'header', 'footer'],
            'view' => 'public.system.blocks.site-menu',
            'fields' => ['title', 'cms_menu_id'],
            'defaults' => ['title' => null, 'cms_menu_id' => null],
            'behavior_key' => 'menu',
            'responsive_behavior' => [
                'desktop' => ['mode' => 'inline'],
                'tablet' => ['mode' => 'inline'],
                'mobile' => ['mode' => 'hamburger', 'panel' => 'drawer', 'drawer_side' => 'right'],
            ],
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'title', 'type' => 'text', 'label_key' => 'components.block_editor.optional_title', 'placeholder_key' => 'components.block_editor.optional_title'],
                    ['name' => 'cms_menu_id', 'type' => 'menu_select', 'label_key' => 'components.block_editor.menu', 'placeholder_key' => 'components.block_editor.choose_menu', 'required' => true],
                ],
            ],
        ],
        'site_login' => [
            'label_key' => 'components.block_editor.site_login',
            'category' => 'header',
            'rendering_mode' => 'safe_blade',
            'zones' => ['header'],
            'view' => 'public.system.blocks.safe-blade',
            'fields' => ['login_label', 'account_label'],
            'defaults' => ['login_label' => 'Login', 'account_label' => 'Account'],
            'safe_blade_template' => '@if(user.is_authenticated)<a class="rw-public-login" href="{{ user.account_url }}">{{ block.account_label }}</a>@else<a class="rw-public-login" href="{{ user.login_url }}">{{ block.login_label }}</a>@endif',
            'preview' => ['title_field' => 'login_label'],
            'editor' => [
                'fields' => [
                    ['name' => 'login_label', 'type' => 'text', 'label_key' => 'components.block_editor.login_label', 'placeholder_key' => 'components.block_editor.login_label_placeholder'],
                    ['name' => 'account_label', 'type' => 'text', 'label_key' => 'components.block_editor.account_label', 'placeholder_key' => 'components.block_editor.account_label_placeholder'],
                ],
            ],
        ],
        'site_user_auth_panel' => [
            'label_key' => 'components.block_editor.site_user_auth_panel',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.site-user-auth-panel',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
            'editor' => ['fields' => []],
        ],
        'site_user_login_form' => [
            'label_key' => 'components.block_editor.site_user_login_form',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.site-user-login-form',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
            'editor' => ['fields' => []],
        ],
        'site_user_register_form' => [
            'label_key' => 'components.block_editor.site_user_register_form',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.site-user-register-form',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
            'editor' => ['fields' => []],
        ],
        'site_user_forgot_password_form' => [
            'label_key' => 'components.block_editor.site_user_forgot_password_form',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.site-user-forgot-password-form',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
            'editor' => ['fields' => []],
        ],
        'site_user_reset_password_form' => [
            'label_key' => 'components.block_editor.site_user_reset_password_form',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.site-user-reset-password-form',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
            'editor' => ['fields' => []],
        ],
        'site_user_dashboard' => [
            'label_key' => 'components.block_editor.site_user_dashboard',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.site-user-dashboard',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
            'editor' => ['fields' => []],
        ],
        'site_user_profile_form' => [
            'label_key' => 'components.block_editor.site_user_profile_form',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.site-user-profile-form',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
            'editor' => ['fields' => []],
        ],
        'site_user_security_settings' => [
            'label_key' => 'components.block_editor.site_user_security_settings',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.site-user-security-settings',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
            'editor' => ['fields' => []],
        ],
        'site_user_two_factor_challenge' => [
            'label_key' => 'components.block_editor.site_user_two_factor_challenge',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['content'],
            'view' => 'public.system.blocks.site-user-two-factor-challenge',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
            'editor' => ['fields' => []],
        ],
        'site_user_account_controls' => [
            'label_key' => 'components.block_editor.site_user_account_controls',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['header', 'footer', 'content'],
            'view' => 'public.system.blocks.site-user-account-controls',
            'fields' => ['guest_icon', 'show_guest_label', 'guest_label', 'account_icon', 'show_account_label', 'account_label'],
            'defaults' => [
                'guest_icon' => 'mdi-account-circle-outline',
                'show_guest_label' => true,
                'guest_label' => null,
                'account_icon' => 'mdi-account-circle-outline',
                'show_account_label' => true,
                'account_label' => null,
            ],
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'guest_icon', 'type' => 'select', 'label_key' => 'components.block_editor.account_guest_icon', 'options' => [
                        ['value' => 'none', 'label_key' => 'components.block_editor.icon_none'],
                        ['value' => 'mdi-account-circle-outline', 'label_key' => 'components.block_editor.account_icon_account_circle'],
                        ['value' => 'mdi-account-outline', 'label_key' => 'components.block_editor.account_icon_account'],
                        ['value' => 'mdi-login', 'label_key' => 'components.block_editor.account_icon_login'],
                        ['value' => 'mdi-lock-outline', 'label_key' => 'components.block_editor.account_icon_lock'],
                        ['value' => 'mdi-shield-account-outline', 'label_key' => 'components.block_editor.account_icon_shield_account'],
                    ]],
                    ['name' => 'show_guest_label', 'type' => 'checkbox', 'label_key' => 'components.block_editor.account_show_guest_label'],
                    ['name' => 'guest_label', 'type' => 'text', 'label_key' => 'components.block_editor.account_guest_label', 'placeholder_key' => 'components.block_editor.account_guest_label_placeholder'],
                    ['name' => 'account_icon', 'type' => 'select', 'label_key' => 'components.block_editor.account_logged_in_icon', 'options' => [
                        ['value' => 'none', 'label_key' => 'components.block_editor.icon_none'],
                        ['value' => 'mdi-account-circle-outline', 'label_key' => 'components.block_editor.account_icon_account_circle'],
                        ['value' => 'mdi-account-outline', 'label_key' => 'components.block_editor.account_icon_account'],
                        ['value' => 'mdi-login', 'label_key' => 'components.block_editor.account_icon_login'],
                        ['value' => 'mdi-lock-outline', 'label_key' => 'components.block_editor.account_icon_lock'],
                        ['value' => 'mdi-shield-account-outline', 'label_key' => 'components.block_editor.account_icon_shield_account'],
                    ]],
                    ['name' => 'show_account_label', 'type' => 'checkbox', 'label_key' => 'components.block_editor.account_show_logged_in_label'],
                    ['name' => 'account_label', 'type' => 'text', 'label_key' => 'components.block_editor.account_logged_in_label', 'placeholder_key' => 'components.block_editor.account_logged_in_label_placeholder'],
                ],
            ],
        ],
        'site_language_switcher' => [
            'label_key' => 'components.block_editor.site_language_switcher',
            'category' => 'header',
            'rendering_mode' => 'platform_blade',
            'zones' => ['header', 'footer'],
            'view' => 'public.system.blocks.site-language-switcher',
            'fields' => ['label_display', 'show_current', 'hide_missing_translations', 'flag_position', 'flag_shape', 'flag_size'],
            'defaults' => [
                'label_display' => 'flag_code',
                'show_current' => true,
                'hide_missing_translations' => true,
                'flag_position' => 'before',
                'flag_shape' => 'rounded',
                'flag_size' => 'normal',
            ],
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'label_display', 'type' => 'select', 'label_key' => 'components.block_editor.language_label_display', 'options' => [
                        ['value' => 'code', 'label_key' => 'components.block_editor.language_label_code'],
                        ['value' => 'name', 'label_key' => 'components.block_editor.language_label_name'],
                        ['value' => 'native_name', 'label_key' => 'components.block_editor.language_label_native_name'],
                        ['value' => 'code_name', 'label_key' => 'components.block_editor.language_label_code_name'],
                        ['value' => 'code_native_name', 'label_key' => 'components.block_editor.language_label_code_native_name'],
                        ['value' => 'flag_only', 'label_key' => 'components.block_editor.language_label_flag_only'],
                        ['value' => 'flag_code', 'label_key' => 'components.block_editor.language_label_flag_code'],
                        ['value' => 'flag_name', 'label_key' => 'components.block_editor.language_label_flag_name'],
                        ['value' => 'flag_native_name', 'label_key' => 'components.block_editor.language_label_flag_native_name'],
                    ]],
                    ['name' => 'show_current', 'type' => 'checkbox', 'label_key' => 'components.block_editor.language_show_current'],
                    ['name' => 'hide_missing_translations', 'type' => 'checkbox', 'label_key' => 'components.block_editor.language_hide_missing_translations'],
                    ['name' => 'flag_position', 'type' => 'select', 'label_key' => 'components.block_editor.language_flag_position', 'options' => [
                        ['value' => 'before', 'label_key' => 'components.block_editor.language_flag_before'],
                        ['value' => 'after', 'label_key' => 'components.block_editor.language_flag_after'],
                    ]],
                    ['name' => 'flag_shape', 'type' => 'select', 'label_key' => 'components.block_editor.language_flag_shape', 'options' => [
                        ['value' => 'rectangle', 'label_key' => 'components.block_editor.language_flag_rectangle'],
                        ['value' => 'rounded', 'label_key' => 'components.block_editor.language_flag_rounded'],
                        ['value' => 'circle', 'label_key' => 'components.block_editor.language_flag_circle'],
                    ]],
                    ['name' => 'flag_size', 'type' => 'select', 'label_key' => 'components.block_editor.language_flag_size', 'options' => [
                        ['value' => 'small', 'label_key' => 'components.block_editor.language_flag_small'],
                        ['value' => 'normal', 'label_key' => 'components.block_editor.language_flag_normal'],
                        ['value' => 'large', 'label_key' => 'components.block_editor.language_flag_large'],
                    ]],
                ],
            ],
        ],
        'site_promo' => [
            'label_key' => 'components.block_editor.site_promo',
            'category' => 'header',
            'rendering_mode' => 'safe_blade',
            'zones' => ['header', 'footer', 'content'],
            'view' => 'public.system.blocks.safe-blade',
            'fields' => ['text', 'link_label', 'link_url', 'open_in_new_tab'],
            'defaults' => ['text' => null, 'link_label' => null, 'link_url' => null, 'open_in_new_tab' => false],
            'safe_blade_template' => '<aside class="rw-public-promo">@if(block.text)<span>{{ block.text }}</span>@endif@if(block.link_url)<a href="{{ block.link_url }}" target="{{ block.target }}" rel="{{ block.rel }}">{{ block.link_label }}</a>@endif</aside>',
            'preview' => ['title_field' => 'text'],
            'editor' => [
                'fields' => [
                    ['name' => 'text', 'type' => 'text', 'label_key' => 'components.block_editor.promo_text', 'placeholder_key' => 'components.block_editor.promo_text_placeholder'],
                    ['name' => 'link_label', 'type' => 'text', 'label_key' => 'components.block_editor.link_label', 'placeholder_key' => 'components.block_editor.link_label_placeholder'],
                    ['name' => 'link_url', 'type' => 'url', 'label_key' => 'components.block_editor.link_url', 'placeholder_key' => 'components.block_editor.link_url_placeholder'],
                    ['name' => 'open_in_new_tab', 'type' => 'checkbox', 'label_key' => 'components.block_editor.open_in_new_tab'],
                ],
            ],
        ],
        'site_link' => [
            'label_key' => 'components.block_editor.site_link',
            'category' => 'navigation',
            'rendering_mode' => 'safe_blade',
            'zones' => ['header', 'footer', 'content'],
            'view' => 'public.system.blocks.site-link',
            'fields' => ['label', 'url', 'open_in_new_tab'],
            'defaults' => ['label' => null, 'url' => null, 'open_in_new_tab' => false],
            'safe_blade_template' => '@if(block.url)<a class="rw-public-site-link" href="{{ block.url }}" target="{{ block.target }}" rel="{{ block.rel }}">{{ block.label }}</a>@endif',
            'preview' => ['title_field' => 'label'],
            'editor' => [
                'fields' => [
                    ['name' => 'label', 'type' => 'text', 'label_key' => 'components.block_editor.link_label', 'placeholder_key' => 'components.block_editor.link_label_placeholder'],
                    ['name' => 'url', 'type' => 'url', 'label_key' => 'components.block_editor.url', 'placeholder_key' => 'components.block_editor.url_placeholder'],
                    ['name' => 'open_in_new_tab', 'type' => 'checkbox', 'label_key' => 'components.block_editor.open_in_new_tab'],
                ],
            ],
        ],
        'site_button' => [
            'label_key' => 'components.block_editor.site_button',
            'category' => 'navigation',
            'rendering_mode' => 'safe_blade',
            'zones' => ['header', 'footer', 'content'],
            'view' => 'public.system.blocks.site-button',
            'fields' => ['label', 'url', 'open_in_new_tab', 'variant'],
            'defaults' => ['label' => null, 'url' => null, 'open_in_new_tab' => false, 'variant' => 'primary'],
            'safe_blade_template' => '@if(block.url)<a class="rw-public-site-button rw-public-site-button--{{ block.variant }}" href="{{ block.url }}" target="{{ block.target }}" rel="{{ block.rel }}">{{ block.label }}</a>@endif',
            'preview' => ['title_field' => 'label'],
            'editor' => [
                'fields' => [
                    ['name' => 'label', 'type' => 'text', 'label_key' => 'components.block_editor.button_label', 'placeholder_key' => 'components.block_editor.button_label_placeholder'],
                    ['name' => 'url', 'type' => 'url', 'label_key' => 'components.block_editor.url', 'placeholder_key' => 'components.block_editor.url_placeholder'],
                    ['name' => 'open_in_new_tab', 'type' => 'checkbox', 'label_key' => 'components.block_editor.open_in_new_tab'],
                    ['name' => 'variant', 'type' => 'select', 'label_key' => 'components.block_editor.variant', 'options' => [
                        ['value' => 'primary', 'label_key' => 'components.block_editor.variant_primary', 'label' => 'Primary'],
                        ['value' => 'secondary', 'label_key' => 'components.block_editor.variant_secondary', 'label' => 'Secondary'],
                    ]],
                ],
            ],
        ],
        'site_html' => [
            'label_key' => 'components.block_editor.site_html',
            'category' => 'content',
            'rendering_mode' => 'safe_blade',
            'zones' => ['header', 'footer', 'content'],
            'view' => 'public.system.blocks.safe-blade',
            'fields' => ['html'],
            'defaults' => ['html' => null],
            'safe_blade_template' => '<div class="rw-public-html">{{ block.html }}</div>',
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'html', 'type' => 'textarea', 'label_key' => 'components.block_editor.html', 'placeholder_key' => 'components.block_editor.html_placeholder', 'rows' => 6],
                ],
            ],
        ],
        'site_raw_html' => [
            'label_key' => 'components.block_editor.site_raw_html',
            'category' => 'code',
            'rendering_mode' => 'raw_code_permissioned',
            'zones' => ['header', 'footer', 'content'],
            'view' => 'public.system.blocks.raw-html',
            'fields' => ['code'],
            'defaults' => ['code' => null],
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'code', 'type' => 'code', 'label_key' => 'common.columns.code', 'language' => 'html', 'rows' => 8],
                ],
            ],
            'requires_permission' => 'admin.cms.layouts.code-blocks.manage',
        ],
        'site_header' => [
            'label_key' => 'layouts.sections.site_header',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['header'],
            'editor_visible' => false,
            'view' => 'public.system.blocks.site-header',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
        ],
        'site_footer' => [
            'label_key' => 'layouts.sections.site_footer',
            'category' => 'system',
            'rendering_mode' => 'platform_blade',
            'zones' => ['footer'],
            'editor_visible' => false,
            'view' => 'public.system.blocks.site-footer',
            'fields' => [],
            'defaults' => [],
            'preview' => ['title_field' => null],
        ],
        'custom_head_code' => [
            'label_key' => 'layouts.sections.custom_head_code',
            'category' => 'code',
            'rendering_mode' => 'raw_code_permissioned',
            'zones' => ['head'],
            'view' => 'public.system.blocks.custom-head-code',
            'fields' => ['code'],
            'defaults' => ['code' => null],
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'code', 'type' => 'code', 'label_key' => 'common.columns.code', 'language' => 'html', 'rows' => 8],
                ],
            ],
            'requires_permission' => 'admin.cms.layouts.code-blocks.manage',
        ],
        'custom_body_end_code' => [
            'label_key' => 'layouts.sections.custom_body_end_code',
            'category' => 'code',
            'rendering_mode' => 'raw_code_permissioned',
            'zones' => ['body_end'],
            'view' => 'public.system.blocks.custom-body-end-code',
            'fields' => ['code'],
            'defaults' => ['code' => null],
            'preview' => ['title_field' => null],
            'editor' => [
                'fields' => [
                    ['name' => 'code', 'type' => 'code', 'label_key' => 'common.columns.code', 'language' => 'html', 'rows' => 8],
                ],
            ],
            'requires_permission' => 'admin.cms.layouts.code-blocks.manage',
        ],
    ],
];
