<?php

return [
    'manifest_type' => 'rwsoft-cms-site-package',
    'version' => 1,
    'implemented_modules' => ['site', 'languages', 'public_texts', 'layouts', 'templates', 'pages', 'menus', 'media', 'downloads', 'themes', 'redirects', 'taxonomies', 'blogs', 'forms', 'docs'],
    'importable_modules' => ['site', 'languages', 'public_texts', 'layouts', 'templates', 'pages', 'menus', 'media', 'downloads', 'themes', 'redirects', 'taxonomies', 'blogs', 'forms', 'docs'],
    'planned_modules' => [],
    'import' => [
        'max_files' => 500,
        'max_json_bytes' => 5 * 1024 * 1024,
        'max_file_bytes' => 10 * 1024 * 1024,
        'allowed_paths' => [
            'manifest.json',
            'site.json',
            'languages.json',
            'public_texts.json',
            'layouts.json',
            'templates.json',
            'pages.json',
            'menus.json',
            'redirects.json',
            'taxonomies.json',
            'posts.json',
            'forms.json',
            'docs.json',
            'site/files/',
            'media/manifest.json',
            'media/files/',
            'downloads/manifest.json',
            'downloads/files/',
            'themes/manifest.json',
            'themes/files/',
        ],
        'allowed_extensions' => ['json', 'css', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'odt', 'ods', 'odp', 'txt', 'csv'],
        'allow_code_blocks_by_default' => false,
    ],
    'policies' => [
        'site' => [
            'settings' => [
                'general.site_name',
                'general.site_tagline',
                'general.default_locale',
                'general.multilingual_enabled',
                'contact.company_name',
                'contact.street',
                'contact.postal_code',
                'contact.city',
                'contact.country',
                'contact.country_code',
                'contact.phone_1_label',
                'contact.phone_1',
                'contact.phone_2_label',
                'contact.phone_2',
                'contact.phone_3_label',
                'contact.phone_3',
                'contact.email_1_label',
                'contact.email_1',
                'contact.email_2_label',
                'contact.email_2',
                'contact.vat_number',
                'contact.image_media_asset_id',
                'performance.public_text_cache_enabled',
                'performance.public_text_cache_ttl',
                'seo.default_title',
                'seo.default_description',
                'seo.global_noindex',
                'seo.h1_min_length',
                'seo.h1_max_length',
                'seo.h2_max_length',
                'seo.h3_max_length',
                'seo.meta_title_min_length',
                'seo.meta_title_max_length',
                'seo.meta_description_min_length',
                'seo.meta_description_max_length',
                'seo.slug_min_length',
                'seo.slug_max_length',
                'seo.url_max_length',
                'seo.content_min_words',
                'seo.require_meta_title_on_publish',
                'seo.require_meta_description_on_publish',
                'seo.require_single_h1',
                'seo.require_valid_heading_hierarchy',
                'seo.require_json_ld',
                'seo.require_og_image_for_posts',
                'seo.robots_extra_rules',
                'branding.company_logo_media_asset_id',
                'branding.logo_path',
                'branding.logo_version',
                'branding.logo_show_tagline',
                'branding.favicon_32_path',
                'branding.favicon_192_path',
                'branding.apple_touch_icon_path',
                'branding.favicon_version',
            ],
        ],
        'layouts' => ['import_active' => false, 'import_default' => false],
        'templates' => ['import_active' => false, 'import_default' => false],
        'pages' => ['import_status' => 'draft', 'import_home' => false],
        'menus' => ['import_active' => false],
        'redirects' => ['import_active' => false],
        'taxonomies' => ['import_active' => false],
        'blogs' => ['import_status' => 'draft'],
        'forms' => ['import_active' => false],
        'docs' => ['import_status' => 'draft'],
        'media' => ['disk' => 'public', 'visibility' => 'public'],
        'downloads' => ['disk' => 'private'],
        'themes' => ['import_active' => false, 'import_status' => 'draft'],
    ],
];
