<?php

return [
    'action_types' => [
        'back',
        'create_record',
        'submit_form',
        'server_action',
        'open_screen',
        'navigate',
        'open_url',
    ],

    'route_names' => [],

    'node_definitions' => [
        'screen' => [
            'allowed_parents' => ['root'],
            'can_have_children' => true,
            'default_props' => [
                'title' => 'Nieuw scherm',
                'showTitle' => true,
                'subtitle' => '',
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'section' => [
            'allowed_parents' => ['screen', 'section', 'tab_panel'],
            'can_have_children' => true,
            'default_props' => [
                'title' => 'Sectie',
                'showTitle' => true,
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'form' => [
            'allowed_parents' => ['screen', 'section', 'card', 'tab_panel'],
            'can_have_children' => true,
            'default_props' => [
                'title' => 'Formulier',
                'showTitle' => true,
                'subtitle' => '',
                'submitAction' => 'screen.form.submit',
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'table' => [
            'allowed_parents' => ['screen', 'section', 'card', 'tab_panel'],
            'can_have_children' => true,
            'default_props' => [
                'title' => 'Tabel',
                'showTitle' => true,
                'dataSourceType' => 'query',
                'queryKey' => '',
                'recordFormScreenKey' => '',
                'columns' => [],
                'initialHeight' => 'calc(100vh - 260px)',
                'tableOptions' => [],
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'inline_group' => [
            'allowed_parents' => ['form', 'section', 'card', 'tab_panel'],
            'can_have_children' => true,
            'default_props' => [
                'gap' => 8,
                'wrapMobile' => true,
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'action_group' => [
            'allowed_parents' => ['form', 'section', 'card', 'table', 'tab_panel'],
            'can_have_children' => true,
            'default_props' => [
                'gap' => 8,
                'justify' => 'split',
                'mobileStack' => true,
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'stack' => [
            'allowed_parents' => ['action_group', 'tab_panel'],
            'can_have_children' => true,
            'default_props' => [
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'card' => [
            'allowed_parents' => ['screen', 'section', 'tab_panel'],
            'can_have_children' => true,
            'default_props' => [
                'title' => 'Kaart',
                'showTitle' => true,
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'tab_bar' => [
            'allowed_parents' => ['screen', 'section', 'form', 'card', 'inline_group', 'action_group', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'tabGroupId' => '',
                'title' => 'Tabs',
                'showTitle' => false,
                'variant' => 'underline',
                'alignment' => 'left',
                'mobileMode' => 'scroll',
                'rememberActiveTab' => false,
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'tab_panel' => [
            'allowed_parents' => ['screen', 'section', 'form', 'card', 'tab_panel'],
            'can_have_children' => true,
            'default_props' => [
                'tabGroupId' => '',
                'tabId' => '',
                'title' => 'Tab',
                'icon' => '',
                'tabColor' => '',
                'textColor' => '',
                'activeTabColor' => '',
                'activeTextColor' => '',
                'bold' => false,
                'badgeText' => '',
                'disabled' => false,
                'sortOrder' => 1,
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'text_block' => [
            'allowed_parents' => ['screen', 'section', 'card', 'form', 'inline_group', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'divider' => [
            'allowed_parents' => ['screen', 'section', 'card', 'form', 'inline_group', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'orientation' => 'horizontal',
                'lineAlign' => 'center',
                'marginTop' => 0,
                'marginBottom' => 0,
                'marginLeft' => 0,
                'marginRight' => 0,
                'paddingTop' => 0,
                'paddingBottom' => 0,
                'paddingLeft' => 0,
                'paddingRight' => 0,
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'text_input' => [
            'allowed_parents' => ['form', 'inline_group', 'card', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'name' => 'field',
                'label' => 'Nieuw veld',
                'required' => false,
                'placeholder' => '',
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'textarea' => [
            'allowed_parents' => ['form', 'inline_group', 'card', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'number_input' => [
            'allowed_parents' => ['form', 'inline_group', 'card', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'date_input' => [
            'allowed_parents' => ['form', 'inline_group', 'card', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'checkbox' => [
            'allowed_parents' => ['form', 'inline_group', 'card', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'booleanDisplay' => 'checkbox',
                'labelPosition' => 'top',
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'select' => [
            'allowed_parents' => ['form', 'inline_group', 'card', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'autocomplete' => [
            'allowed_parents' => ['form', 'inline_group', 'card', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'radio_group' => [
            'allowed_parents' => ['form', 'inline_group', 'card', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'action_button' => [
            'allowed_parents' => ['form', 'table', 'inline_group', 'action_group', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'label' => 'Actie',
                'icon' => 'mdi mdi-lightning-bolt',
                'tone' => 'neutral',
                'variant' => 'default',
                'actionType' => 'submit_form',
                'alignment' => 'right',
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
        'file_upload' => [
            'allowed_parents' => ['form', 'inline_group', 'card', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'name' => 'file',
                'label' => 'Bestand',
                'required' => false,
                'uploadKind' => 'document',
                'visibility' => 'private',
                'inputMode' => 'drag_drop_and_picker',
                'allowedExtensions' => ['pdf', 'doc', 'docx', 'odt', 'svg'],
                'maxSizeMb' => 10,
                'previewMode' => 'icon',
                'allowReplace' => true,
                'allowRemove' => true,
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
                'imageProcessing' => [
                    'enabled' => false,
                    'outputFormat' => 'webp',
                    'quality' => 82,
                    'keepOriginal' => false,
                    'variants' => [
                        ['key' => 'thumb', 'width' => 240, 'height' => 240, 'fit' => 'cover'],
                        ['key' => 'medium', 'width' => 900, 'height' => null, 'fit' => 'contain'],
                    ],
                ],
            ],
        ],
        'multi_file_upload' => [
            'allowed_parents' => ['form', 'inline_group', 'card', 'stack', 'tab_panel'],
            'can_have_children' => false,
            'default_props' => [
                'name' => 'files',
                'label' => 'Bestanden',
                'required' => false,
                'maxSizeMb' => 10,
                'maxFiles' => 10,
                'cardColumnsDesktop' => 5,
                'cardColumnsTablet' => 3,
                'cardColumnsMobile' => 1,
                'cardThumbnailHeight' => 'large',
                'resetRuntimeCardColumnsOnViewportChange' => true,
                'sortable' => true,
                'allowRemove' => true,
                'allowReplace' => true,
                'showPreviewList' => true,
                'previewMode' => 'thumbnail_with_meta',
                'previewDisplayMode' => 'list',
                'visibilityMode' => 'visible',
                'permissionMode' => 'all',
            ],
        ],
    ],
];
