<?php

return [
    'preserve_unknown_placeholders' => true,
    'preserve_unauthorized_placeholders' => true,

    'contexts' => [
        'public_site.auth_email' => [
            'allowed' => [
                'user.name',
                'user.email',
                'site.name',
                'site.url',
                'action.url',
                'action.expires_at',
            ],
            'labels' => [
                'user.name' => 'Gebruikersnaam',
                'user.email' => 'E-mailadres gebruiker',
                'site.name' => 'Sitenaam',
                'site.url' => 'Website URL',
                'action.url' => 'Veilige actielink',
                'action.expires_at' => 'Vervalt op',
            ],
        ],
        'cms.form_submission.email' => [
            'allowed' => [
                'form.id',
                'form.title',
                'form.locale',
                'submission.id',
                'submission.submitted_at',
                'submission.status',
                'page.id',
                'page.title',
                'site.name',
                'site.url',
            ],
            'labels' => [
                'form.id' => 'Formulier ID',
                'form.title' => 'Formuliertitel',
                'form.locale' => 'Formuliertaal',
                'submission.id' => 'Inzending ID',
                'submission.submitted_at' => 'Datum inzending',
                'submission.status' => 'Status inzending',
                'page.id' => 'Pagina ID',
                'page.title' => 'Paginatitel',
                'site.name' => 'Sitenaam',
                'site.url' => 'Website URL',
            ],
        ],
        'cms.page.json_ld' => [
            'allowed' => [
                'page.title',
                'page.short_description',
                'page.seo_title',
                'page.seo_description',
                'page.url',
                'page.published_at',
                'page.updated_at',
                'site.name',
                'site.url',
            ],
            'labels' => [
                'page.title' => 'Paginatitel',
                'page.short_description' => 'Korte omschrijving',
                'page.seo_title' => 'SEO titel',
                'page.seo_description' => 'SEO omschrijving',
                'page.url' => 'Publieke pagina URL',
                'page.published_at' => 'Publicatiedatum',
                'page.updated_at' => 'Laatste wijziging',
                'site.name' => 'Sitenaam',
                'site.url' => 'Website URL',
            ],
        ],
        'cms.post.json_ld' => [
            'allowed' => [
                'post.title',
                'post.excerpt',
                'post.seo_title',
                'post.seo_description',
                'post.url',
                'post.published_at',
                'post.updated_at',
                'post.featured_image_url',
                'post.categories',
                'post.tags',
                'site.name',
                'site.url',
            ],
            'labels' => [
                'post.title' => 'Berichttitel',
                'post.excerpt' => 'Intro',
                'post.seo_title' => 'SEO titel',
                'post.seo_description' => 'SEO omschrijving',
                'post.url' => 'Publieke bericht URL',
                'post.published_at' => 'Publicatiedatum',
                'post.updated_at' => 'Laatste wijziging',
                'post.featured_image_url' => 'Uitgelichte afbeelding URL',
                'post.categories' => 'Categorieen',
                'post.tags' => 'Tags',
                'site.name' => 'Sitenaam',
                'site.url' => 'Website URL',
            ],
        ],
    ],
];
